export type Dish = {
  id: string;
  local_name?: string;
  english_name: string;
  description?: string;
  countries?: string[];
  recipe?: string;
  public_cc_image_url?: string;
  language?: string;
  language_code?: string;
  continent?: string;
  regions?: string;
  cultures?: string;
  time_of_day?: string;
  time_of_day_more?: string;
  type_of_dish?: string;
  type_of_dish_more?: string;
  utensils?: string;
  drink?: string;
  occasions?: string;
  occasions_more?: string;
  ingredients?: string;
  more_details?: string;
  public_cc_image_caption?: string;
  uploaded_image_name?: string;
  uploaded_image_url?: string;
  uploaded_image_caption?: string;
};